### ISSUE TITLE
Letsencrypt: Timeout error

### ISSUE THREAD

**Issue by renatobellotti** [nextcloud/docker#1017]
Hello,

I'm currently having problems with the Nginx-Proxy-Letsencrypt setup. I'm using the configuration from the repo at `.examples/docker-compose/with-nginx-proxy/mariadb`. If I understood correctly, this image should work "out-of-the-box" (after setting the passwords, of course).

However, when I run `docker-compose up`, there seems to be a timeout with letsencrypt:

```
letsencrypt-companion_1  | Reloading nginx proxy (cde5ed934b90ed4e76f9d82d7ec99aeaf776cd22c913c56ee9a0c614a3a9c5d3)...
letsencrypt-companion_1  | 2020/03/03 21:30:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
letsencrypt-companion_1  | 2020/03/03 21:30:28 [notice] 43#43: signal process started
letsencrypt-companion_1  | 2020/03/03 21:30:29 Generated '/app/letsencrypt_service_data' from 5 containers
letsencrypt-companion_1  | 2020/03/03 21:30:29 Running '/app/signal_le_service'
letsencrypt-companion_1  | 2020/03/03 21:30:29 Watching docker events
letsencrypt-companion_1  | 2020/03/03 21:30:29 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt-companion_1  | /etc/nginx/certs/renatobellotti.ch /app
letsencrypt-companion_1  | Reloading nginx proxy (cde5ed934b90ed4e76f9d82d7ec99aeaf776cd22c913c56ee9a0c614a3a9c5d3)...
letsencrypt-companion_1  | 2020/03/03 21:30:31 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
letsencrypt-companion_1  | 2020/03/03 21:30:31 [notice] 62#62: signal process started
letsencrypt-companion_1  | Creating/renewal renatobellotti.ch certificates... (renatobellotti.ch)
letsencrypt-companion_1  | 2020-03-03 21:30:34,044:INFO:simp_le:1323: Generating new account key
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
letsencrypt-companion_1  |     (self._dns_host, self.port), self.timeout, **extra_kw
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
letsencrypt-companion_1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
letsencrypt-companion_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
letsencrypt-companion_1  | socket.gaierror: [Errno -3] Try again
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
letsencrypt-companion_1  |     chunked=chunked,
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
letsencrypt-companion_1  |     self._validate_conn(conn)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
letsencrypt-companion_1  |     conn.connect()
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
letsencrypt-companion_1  |     conn = self._new_conn()
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
letsencrypt-companion_1  |     self, "Failed to establish a new connection: %s" % e
letsencrypt-companion_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
letsencrypt-companion_1  |     timeout=timeout
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
letsencrypt-companion_1  |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
letsencrypt-companion_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
letsencrypt-companion_1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again'))
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
letsencrypt-companion_1  |     return main_with_exceptions(cli_args)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
letsencrypt-companion_1  |     persist_new_data(args, existing_data)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1408, in persist_new_data
letsencrypt-companion_1  |     args, existing_data.account_key, existing_data.account_reg)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1341, in registered_client
letsencrypt-companion_1  |     directory = messages.Directory.from_json(net.get(args.server).json())
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/acme/client.py", line 1161, in get
letsencrypt-companion_1  |     self._send_request('GET', url, **kwargs), content_type=content_type)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
letsencrypt-companion_1  |     response = self.session.request(method, url, *args, **kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
letsencrypt-companion_1  |     resp = self.send(prep, **send_kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
letsencrypt-companion_1  |     r = adapter.send(request, **kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
letsencrypt-companion_1  |     raise ConnectionError(e, request=request)
letsencrypt-companion_1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again'))
letsencrypt-companion_1  | Reloading nginx proxy (cde5ed934b90ed4e76f9d82d7ec99aeaf776cd22c913c56ee9a0c614a3a9c5d3)...
letsencrypt-companion_1  | 2020/03/03 21:30:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
letsencrypt-companion_1  | 2020/03/03 21:30:28 [notice] 43#43: signal process started
letsencrypt-companion_1  | 2020/03/03 21:30:29 Generated '/app/letsencrypt_service_data' from 5 containers
letsencrypt-companion_1  | 2020/03/03 21:30:29 Running '/app/signal_le_service'
letsencrypt-companion_1  | 2020/03/03 21:30:29 Watching docker events
letsencrypt-companion_1  | 2020/03/03 21:30:29 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
letsencrypt-companion_1  | /etc/nginx/certs/renatobellotti.ch /app
letsencrypt-companion_1  | Reloading nginx proxy (cde5ed934b90ed4e76f9d82d7ec99aeaf776cd22c913c56ee9a0c614a3a9c5d3)...
letsencrypt-companion_1  | 2020/03/03 21:30:31 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''
letsencrypt-companion_1  | 2020/03/03 21:30:31 [notice] 62#62: signal process started
letsencrypt-companion_1  | Creating/renewal renatobellotti.ch certificates... (renatobellotti.ch)
letsencrypt-companion_1  | 2020-03-03 21:30:34,044:INFO:simp_le:1323: Generating new account key
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
letsencrypt-companion_1  |     (self._dns_host, self.port), self.timeout, **extra_kw
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
letsencrypt-companion_1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
letsencrypt-companion_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
letsencrypt-companion_1  | socket.gaierror: [Errno -3] Try again
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
letsencrypt-companion_1  |     chunked=chunked,
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
letsencrypt-companion_1  |     self._validate_conn(conn)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
letsencrypt-companion_1  |     conn.connect()
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
letsencrypt-companion_1  |     conn = self._new_conn()
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
letsencrypt-companion_1  |     self, "Failed to establish a new connection: %s" % e
letsencrypt-companion_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
letsencrypt-companion_1  |     timeout=timeout
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
letsencrypt-companion_1  |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
letsencrypt-companion_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
letsencrypt-companion_1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again'))
letsencrypt-companion_1  | 
letsencrypt-companion_1  | During handling of the above exception, another exception occurred:
letsencrypt-companion_1  | 
letsencrypt-companion_1  | Traceback (most recent call last):
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
letsencrypt-companion_1  |     return main_with_exceptions(cli_args)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
letsencrypt-companion_1  |     persist_new_data(args, existing_data)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1408, in persist_new_data
letsencrypt-companion_1  |     args, existing_data.account_key, existing_data.account_reg)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/simp_le.py", line 1341, in registered_client
letsencrypt-companion_1  |     directory = messages.Directory.from_json(net.get(args.server).json())
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/acme/client.py", line 1161, in get
letsencrypt-companion_1  |     self._send_request('GET', url, **kwargs), content_type=content_type)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
letsencrypt-companion_1  |     response = self.session.request(method, url, *args, **kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
letsencrypt-companion_1  |     resp = self.send(prep, **send_kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
letsencrypt-companion_1  |     r = adapter.send(request, **kwargs)
letsencrypt-companion_1  |   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
letsencrypt-companion_1  |     raise ConnectionError(e, request=request)
letsencrypt-companion_1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3f5266a190>: Failed to establish a new connection: [Errno -3] Try again'))
```

After that, I can access the website and see the dialogue for the first time setup of NextCloud, but when I add `https://` to the URL, I get `Internal Server Error 500`.

Has somebody faced similar issues? I'm happy about any help. :)

**Comment by renatobellotti** [comment]
I've been able to solve the issue. There was a problem with name resolution in my IPv6 only VM. I've switched to IPv4, and now the error disappears.
