### ISSUE TITLE
Docker-compose build issue

### ISSUE THREAD

**Issue by perariontaeadastra** [nextcloud/docker#1052]
Hi.

I am new to docker, but I managed to build an image from the base one. But, as a new update rolls out and I try to re-build my image, I get some errors. I also have a custom nginx:alpine image, which generates same error. Can't figure out what to do. Appreciate any help:

**docker-compose -f docker-compose.yml build --pull
proxy uses an image, skipping
letsencrypt uses an image, skipping
redis uses an image, skipping
db uses an image, skipping
phpmyadmin uses an image, skipping
Building app
Traceback (most recent call last):
  File "site-packages/docker/utils/build.py", line 97, in create_archive
  File "tarfile.py", line 1967, in addfile
  File "tempfile.py", line 481, in func_wrapper
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 304, in build
  File "compose/project.py", line 397, in build
  File "compose/project.py", line 380, in build_service
  File "compose/service.py", line 1104, in build
  File "site-packages/docker/api/build.py", line 160, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 100, in create_archive
OSError: Can not read file in context: /nextcloud17app/app/data/appdata_oct0ejkbadbn/preview/16798/64-64-crop.jpg
[27973] Failed to execute script docker-compose**

**Comment by SlavikCA** [comment]
I'm getting same error.

@perariontaeadastra , Have you found a solution?

**Comment by isdnfan** [comment]
I hit similar issues when tried to build new image - running docker-compose build twice fixed the issue (second run is successful). I'm not sure this is a general problem as my docker is running on QNAP NAS which may issue some problems especially in terms of performance

**Comment by joshtrichards** [comment]
Hi folks - I'm going to close this issue out since it's been 3+ years and also sounds like a general Docker matter (rather than a a bug report specific to the Nextcloud community Docker image).  Hopefully you've found a solution on your own or through another channel. If not, I suggest the Docker Community Forums: https://forums.docker.com/ or even the Nextcloud Help Forum: https://help.nextcloud.com.
