### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by manusaxo** [nextcloud/docker#1319]
Hello everyone.

When I want to connect via browser to my Nextcloud server the following message appears: 

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

In the log from my Nextcloud docker I have :

```
Initializing nextcloud 20.0.3.2 ...,
Upgrading nextcloud from 20.0.2.2 ...,
Initializing finished,
An unhandled exception has been thrown:,
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/lib/private/DB/Connection.php:72,
Stack trace:,
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1449): OC\DB\Connection->connect(),
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(892): Doctrine\DBAL\Connection->getWrappedConnection(),
#2 /var/www/html/lib/private/DB/Connection.php(202): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL),
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery('SELECT * FROM `...', Array, Array),
#4 /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php(217): Doctrine\DBAL\Query\QueryBuilder->execute(),
#5 /var/www/html/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute(),
#6 /var/www/html/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues(),
#7 /var/www/html/lib/private/AppConfig.php(301): OC\AppConfig->getApps(),
#8 /var/www/html/lib/private/legacy/OC_App.php(949): OC\AppConfig->getValues(false, 'installed_versi...'),
#9 /var/www/html/lib/private/Server.php(668): OC_App::getAppVersions(),
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server)),
#11 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)),
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Memcache\\Fac...'),
#13 /var/www/html/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', true),
#14 /var/www/html/lib/private/Server.php(1677): OC\ServerContainer->query('OC\\Memcache\\Fac...'),
#15 /var/www/html/lib/private/Server.php(1017): OC\Server->getMemCacheFactory(),
#16 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server)),
#17 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)),
#18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...'),
#19 /var/www/html/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', true),
#20 /var/www/html/lib/private/Server.php(1977): OC\ServerContainer->query('OCP\\Lock\\ILocki...'),
#21 /var/www/html/lib/private/Files/View.php(118): OC\Server->getLockingProvider(),
#22 /var/www/html/lib/private/Server.php(395): OC\Files\View->__construct(),
#23 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server)),
#24 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container)),
#25 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OC\\Files\\Node\\H...'),
#26 /var/www/html/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', true),
#27 /var/www/html/lib/private/Server.php(1324): OC\ServerContainer->query('OC\\Files\\Node\\H...'),
#28 /var/www/html/lib/base.php(595): OC\Server->boot(),
#29 /var/www/html/lib/base.php(1091): OC::init(),
#30 /var/www/html/console.php(49): require_once('/var/www/html/l...'),
#31 /var/www/html/occ(11): require_once('/var/www/html/c...'),,
n}�AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message,
[Sat Dec 12 00:06:09.982094 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.13 configured -- resuming normal operations,
[Sat Dec 12 00:06:09.982126 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
172.17.0.1 - - [12/Dec/2020:00:06:11 +0000] "GET /remote.php/webdav/ HTTP/1.1" 500 717 "-" "-",
172.17.0.1 - - [12/Dec/2020:00:06:13 +0000] "GET /remote.php/webdav/ HTTP/1.1" 500 717 "-" "-",
172.17.0.1 - - [12/Dec/2020:00:06:14 +0000] "GET /remote.php/webdav/ HTTP/1.1" 500 717 "-" "-",
172.17.0.1 - - [12/Dec/2020:00:15:14 +0000] "GET / HTTP/1.1" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
172.17.0.1 - - [12/Dec/2020:00:15:14 +0000] "GET /favicon.ico HTTP/1.1" 404 702 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
172.17.0.1 - - [12/Dec/2020:00:15:17 +0000] "GET / HTTP/1.1" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
172.17.0.1 - - [12/Dec/2020:00:15:19 +0000] "GET / HTTP/1.1" 500 717 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",

```

**Comment by J0WI** [comment]
Looks like your database credentials are wrong.
