### ISSUE TITLE
ERROR: relation "oc_migrations" already exists

### ISSUE THREAD

**Issue by jakubgs** [nextcloud/docker#1529]
I'm running the `nextcloud:21.0.3-apache` image and sometimes when I re-create the container it just fails to start:
```
Previous: PDOException: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "oc_migrations" already exists
Trace: #0 /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php(82): PDO->query('CREATE TABLE oc...')
#1 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1035): Doctrine\DBAL\Driver\PDO\Connection->query('CREATE TABLE oc...')
#2 /var/www/html/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE oc...', Array, Array, NULL)
#3 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1757): OC\DB\Connection->executeQuery('CREATE TABLE oc...')
#4 /var/www/html/lib/private/DB/Migrator.php(256): Doctrine\DBAL\Connection->query('CREATE TABLE oc...')
#5 /var/www/html/lib/private/DB/Migrator.php(90): OC\DB\Migrator->applySchema(Object(Doctrine\DBAL\Schema\Schema))
#6 /var/www/html/lib/private/DB/Connection.php(524): OC\DB\Migrator->migrate(Object(Doctrine\DBAL\Schema\Schema))
#7 /var/www/html/lib/private/DB/MigrationService.php(178): OC\DB\Connection->migrateToSchema(Object(Doctrine\DBAL\Schema\Schema))
#8 /var/www/html/lib/private/DB/MigrationService.php(192): OC\DB\MigrationService->createMigrationTable()
#9 /var/www/html/lib/private/DB/MigrationService.php(265): OC\DB\MigrationService->getMigratedVersions()
#10 /var/www/html/lib/private/DB/MigrationService.php(443): OC\DB\MigrationService->getMigrationsToExecute('latest')
#11 /var/www/html/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly('latest')
#12 /var/www/html/lib/private/Setup/AbstractDatabase.php(154): OC\DB\MigrationService->migrate('latest', true)
#13 /var/www/html/lib/private/Setup.php(378): OC\Setup\AbstractDatabase->runMigrations()
#14 /var/www/html/core/Command/Maintenance/Install.php(108): OC\Setup->install(Array)
#15 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/console.php(100): OC\Console\Application->run()
#21 /var/www/html/occ(11): require_once('/var/www/html/c...')
#22 {main}
retrying install...
```
And it's acting as if it's not configured at all and it's it's first startup, which it isn't:

![image](https://user-images.githubusercontent.com/2212681/124582592-6ea62980-de52-11eb-9daf-b97803791f3b.png)

No idea what I'm supposed to do with this. I haven't touched the database, I just re-created the container...

**Comment by jakubgs** [comment]
I'm actually not sure if this should not be moved to the `server` repo. Maybe the issue isn't related to the docker image.

**Comment by jakubgs** [comment]
What's also weird is that it's asking me to `Create an admin account` but I can clearly is it existing in the database:
```
nextcloud=# SELECT * FROM oc_users;
  uid  | displayname |                                              password                                               | uid_lower 
-------+-------------+-----------------------------------------------------------------------------------------------------+-----------
 admin |             | 3|$argon2id$v=19$m=65536,t=4,p=1$aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa | admin
(1 row)
```
So what is that about?

**Comment by jakubgs** [comment]
I modified the `entrypoint.sh` and added `-vvv` to the `occ maintenance:install` call and got this:
```
Installing with PostgreSQL database
starting nextcloud installation
In ExceptionConverter.php line 83:
                                                                               
  [Doctrine\DBAL\Exception\DriverException (7)]                                
  An exception occurred while executing a query: An exception occurred while   
  executing a query: SQLSTATE[HY000]: General error: 7 server closed the conn  
  ection unexpectedly                                                          
  #011This probably means the server terminated abnormally                        
  #011before or while processing the request.                                     
                                                                               
Exception trace:
  at /var/www/html/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:83
 Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert() at /var/www/html/3rdparty/doctrine/dbal/src/Connection.php:1728
 Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/3rdparty/doctrine/dbal/src/Connection.php:1667
 Doctrine\DBAL\Connection->convertExceptionDuringQuery() at /var/www/html/3rdparty/doctrine/dbal/src/Connection.php:525
 Doctrine\DBAL\Connection->fetchOne() at /var/www/html/3rdparty/doctrine/dbal/src/Connection.php:213
 Doctrine\DBAL\Connection->getDatabase() at /var/www/html/3rdparty/doctrine/dbal/src/Schema/AbstractSchemaManager.php:317
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableForeignKeys() at /var/www/html/3rdparty/doctrine/dbal/src/Schema/AbstractSchemaManager.php:280
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /var/www/html/3rdparty/doctrine/dbal/src/Schema/PostgreSQLSchemaManager.php:512
 Doctrine\DBAL\Schema\PostgreSQLSchemaManager->listTableDetails() at /var/www/html/3rdparty/doctrine/dbal/src/Schema/AbstractSchemaManager.php:261
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /var/www/html/3rdparty/doctrine/dbal/src/Schema/AbstractSchemaManager.php:1074
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /var/www/html/lib/private/DB/Migrator.php:188
 OC\DB\Migrator->createSchema() at /var/www/html/lib/private/DB/Connection.php:511
 OC\DB\Connection->createSchema() at /var/www/html/lib/private/DB/SchemaWrapper.php:43
 OC\DB\SchemaWrapper->__construct() at /var/www/html/lib/private/DB/MigrationService.php:454
 OC\DB\MigrationService->OC\DB\{closure}() at /var/www/html/apps/contactsinteraction/lib/Migration/Version010000Date20200304152605.php:45
 OCA\ContactsInteraction\Migration\Version010000Date20200304152605->changeSchema() at /var/www/html/lib/private/DB/MigrationService.php:455
 OC\DB\MigrationService->migrateSchemaOnly() at /var/www/html/lib/private/DB/MigrationService.php:418
 OC\DB\MigrationService->migrate() at /var/www/html/lib/private/Installer.php:623
 OC\Installer::installShippedApp() at /var/www/html/lib/private/Installer.php:586
 OC\Installer::installShippedApps() at /var/www/html/lib/private/Setup.php:411
 OC\Setup->install() at /var/www/html/core/Command/Maintenance/Install.php:108
 OC\Core\Command\Maintenance\Install->execute() at /var/www/html/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/3rdparty/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/3rdparty/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/3rdparty/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:215
 OC\Console\Application->run() at /var/www/html/console.php:100
 require_once() at /var/www/html/occ:11
```

**Comment by jakubgs** [comment]
What's also interesting is that this failure of `occ` command does not cause it to return a non-zero exit code.

**Comment by jakubgs** [comment]
If I comment out the `occ` command and run it by hand later it works fine:
```
admin@node-01.do-ams3.nextcloud.misc:/docker % d exec -it -u www-data nextcloud-app bash
www-data@03c7f340336a:~/html$ php /var/www/html/occ maintenance:install -vvv -n --admin-user "$NEXTCLOUD_ADMIN_USER" --admin-pass "$NEXTCLOUD_ADMIN_PASSWORD" --data-dir "$NEXTCLOUD_DATA_DIR" --database pgsql --database-name "$POSTGRES_DB" --database-user "$POSTGRES_USER" --database-pass "$POSTGRES_PASSWORD" --database-host "$POSTGRES_HOST"
Nextcloud was successfully installed
```

**Comment by jakubgs** [comment]
It looks like the whole script crashes, because I can see this line again:
```
Configuring Redis as session handler
```

**Comment by jakubgs** [comment]
I have figured it out. It was use of `restarted: true` with `docker_compose` from Ansible:
```yaml
- name: Create service containers
  docker_compose:
    project_src: '{{ nextcloud_service_path }}'
    state: '{{ compose_state }}'
    recreate: '{{ compose_recreate }}'
    restarted: '{{ logs_conf.changed or compose_restart }}'
    pull: true
```
Because at installation `logs_conf.changed` was always true it would cause it to restart roughly 10 seconds after creation.

This would interrupt the installation process ran via `occ` and leave NextCloud in a broken state.
It also caused the `entrypoint.sh` script and `occ` command to return no error, since it was just killed by Docker.

**Comment by 2fst4u** [comment]
Can you elaborate on how you resolved this? I'm getting this on an entirely fresh docker install but I'm not using ansible like you were.

**Comment by jmsulli6464** [comment]
I had the same issue where Nextcloud was failing to download apps. After some digging, I discovered the problem stemmed from how I had configured the log volume in my docker-compose.

Pointing next cloud logs to a different location caused the issue and I just had to remove the mapping to allow it to default and that fixed the trick

eg
`  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /Containers/volumes/nextcloud_data:/var/www/html/data
      - /Containers/Configs/nextcloud_config:/var/www/html/config
      - /Containers/Logs/nextcloud_logs:/var/www/html/data/nextcloud.log  {removed this line) `
