### ISSUE TITLE
 [BUG] Nextcloud 24 upgrade fail - bool given in /var/www/html/lib/private/Security/CertificateManager.php #1747 

### ISSUE THREAD

**Issue by supermar1010** [nextcloud/docker#1801]
I have the same issue as here: https://github.com/nextcloud/docker/issues/1747
But the solution proposed there does not work for me. My nextcloud uses a S3 bucket as primary storage. If this is not related to docker, I'll post it in the main repo, I hust thought it might have something to do with the containerization.

My permissions inside the container look like this:

```
drwxr-xr-x. 11 www-data root          4096 Jan  3  2021 appdata_ocpjd1r214qj.bak
drwxr-xr-x.  2 www-data www-data      4096 Jan  2  2021 files_external
-rw-r--r--.  1 www-data root             0 Aug  8 14:30 index.html
drwxr-xr-x.  2 www-data root          4096 Jan  3  2021 some_username
-rw-r-----.  1 www-data www-data  64547927 Aug  8 14:30 nextcloud.log
-rw-r-----.  1 www-data www-data 104867462 Jul 13 00:40 nextcloud.log.1
drwxr-xr-x.  2 www-data root          4096 Jan  3  2021 root

```

Log output
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
An unhandled exception has been thrown:
TypeError: Cannot assign bool to property OC\Security\CertificateManager::$bundlePath of type ?string in /var/www/html/lib/private/Security/CertificateManager.php:250
Stack trace:
#0 /var/www/html/lib/private/Http/Client/Client.php(127): OC\Security\CertificateManager->getAbsoluteBundlePath()
#1 /var/www/html/lib/private/Http/Client/Client.php(74): OC\Http\Client\Client->getCertBundle()
#2 /var/www/html/lib/private/Http/Client/Client.php(218): OC\Http\Client\Client->buildRequestOptions(Array)
#3 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(120): OC\Http\Client\Client->get('https://apps.ne...', Array)
#4 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(87): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#5 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(192): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '', false)
#6 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(188): OC\App\AppStore\Fetcher\Fetcher->get(false)
#7 /var/www/html/lib/private/Installer.php(422): OC\App\AppStore\Fetcher\AppFetcher->get(false)
#8 /var/www/html/lib/private/Updater.php(413): OC\Installer->isUpdateAvailable('accessibility')
#9 /var/www/html/lib/private/Updater.php(274): OC\Updater->upgradeAppStoreApps(Array)
#10 /var/www/html/lib/private/Updater.php(133): OC\Updater->doUpgrade('24.0.3.2', '23.0.3.2')
#11 /var/www/html/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#12 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/console.php(100): OC\Console\Application->run()
#18 /var/www/html/occ(11): require_once('/var/www/html/c...')
#19 {main}
```

**Comment by supermar1010** [comment]
I'd like to disagree that it is a duplicate. I read the proposed solution but the access rights were right for me already. SO i guess it has something to with me using S3 as a primary storage provider
