### ISSUE TITLE
Missing dependencies, broken background jobs

### ISSUE THREAD

**Issue by QuaiGoner** [nextcloud/docker#1838]
Hello, i am running freshly installed latest docker image (24.0.6)

I wanted to install Memories and Recognize apps and checked on the background jobs that stated they were not running for the last 3 days. I was using AJAX  as a job scheduler.
By documentation recommended is cron, so i turned that on, but found out that cron packgae is not even there in the docker image.
So i installed folollowing dependencies in the container via docker exec: libimage-exiftool-perl wget gnupg2 unzip ffmpeg git make systemctl cron

Enabled and started cron service, but background jobs are still not running. thats an issue number 1
manually starting cron.php resulting in this error below:
![image](https://user-images.githubusercontent.com/41058180/195971173-d2950b9e-c2c5-4bd4-a7d5-7aa7dbe427f4.png)

Second issue is now working recognize app and error in the logs 
![image](https://user-images.githubusercontent.com/41058180/195971180-fc6bc913-45a2-4c96-ae52-a74a5278a034.png)

Really bummed out by these errors and amount of CLI fiddling required to run that container. Is that fixable? Thank you

**Comment by steve-todorov** [comment]
I've been trying to get this to work in k8s as well. Cron tasks are completely broken. 
The documentation states you should run the task under `www-data`, but that user is disabled. 
The default `/etc/cronttab/www-data` file runs the `cron.php` file as `root`, but even then I get:
```
#0 lib/base.php(670): OC::checkInstalled(Object(OC\SystemConfig))
#1 lib/base.php(1111): OC::init()
#2 cron.php(43): require_once('lib/base.p...')
```

No idea what's going on, but it's blowing up everywhere.
I also get the `allowed memory size exhausted`  error when I try to login to the container and manually run `php -f cron.php`.

**Comment by steve-todorov** [comment]
I am already using a different container to run only the cron task. The issue was related to the bad practice of having to copy files from /usr/src/nextcloud into /var/www/html. There were missing files which caused various exceptions.
