### ISSUE TITLE
Custom Entrypoint Hook stopped working after Update to 27.0.1

### ISSUE THREAD

**Issue by mueller-tobias** [nextcloud/docker#2053]
I've used the Custom Entrypoint Hook to install some apps and make customzation to our nextcloud instance. With the Upgrade to 27.0.1 it's not working anymore and i can't figure out why.

In my script i run several commands like this:

```
#!/bin/sh
set -eu

run_as() {
    if [ "$(id -u)" = 0 ]; then
        su -s /bin/sh www-data -c "php occ $1"
    else
        sh -c "php occ $1"
    fi
}

echo User ID
id
id -u

echo Path
pwd

echo Disable App
run_as app:disable dashboard
```

This was working fine with the nextcloud:27.0.0-apache. But with nextcloud:27.0.1-apache i get some strange errors:

```
Configuring Redis as session handler
2023-08-11T14:30:10.962928779Z => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
2023-08-11T14:30:10.964568420Z ==> Running the script (cwd: /var/www/html): "/docker-entrypoint-hooks.d/before-starting/00_post-start.sh"
2023-08-11T14:30:10.970829593Z User ID
2023-08-11T14:30:10.971687017Z uid=33(www-data) gid=33(www-data) groups=33(www-data)
2023-08-11T14:30:10.972543992Z 33
2023-08-11T14:30:10.972682489Z Path
2023-08-11T14:30:10.972694072Z /var/www/html
2023-08-11T14:30:10.972697292Z Disable App
2023-08-11T14:30:11.189592022Z An unhandled exception has been thrown:
2023-08-11T14:30:11.189632517Z Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "estest-postgresql" (10.43.215.250), port 5432 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
2023-08-11T14:30:11.189642658Z connection to server at "estest-postgresql" (10.43.215.250), port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "10.42.29.203", user "nextcloud", database "nextcloud", no encryption in /var/www/html/lib/private/DB/Connection.php:140
Stack trace:
2023-08-11T14:30:11.189649507Z #0 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect()
2023-08-11T14:30:11.189653546Z #1 /var/www/html/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /var/www/html/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM "...', Array, Array, NULL)
2023-08-11T14:30:11.189660112Z #3 /var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\DB\Connection->executeQuery('SELECT * FROM "...', Array, Array)
#4 /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php(280): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /var/www/html/lib/private/AppConfig.php(418): OC\DB\QueryBuilder\QueryBuilder->execute()
2023-08-11T14:30:11.189668743Z #6 /var/www/html/lib/private/AppConfig.php(184): OC\AppConfig->loadConfigValues()
2023-08-11T14:30:11.189671784Z #7 /var/www/html/lib/private/AppConfig.php(374): OC\AppConfig->getApps()
2023-08-11T14:30:11.189674585Z #8 /var/www/html/lib/private/legacy/OC_App.php(803): OC\AppConfig->getValues(false, 'installed_versi...')
2023-08-11T14:30:11.189677347Z #9 /var/www/html/lib/private/Server.php(733): OC_App::getAppVersions()
2023-08-11T14:30:11.189680080Z #10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
2023-08-11T14:30:11.189683917Z #11 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
2023-08-11T14:30:11.189686794Z #12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
2023-08-11T14:30:11.189689532Z #13 /var/www/html/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...', true)
2023-08-11T14:30:11.189693479Z #14 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(193): OC\AppFramework\Utility\SimpleContainer->get('OC\\Memcache\\Fac...')
2023-08-11T14:30:11.189702042Z #16 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
2023-08-11T14:30:11.189721449Z #18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCP\\ICacheFacto...')
2023-08-11T14:30:11.189725047Z #19 /var/www/html/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OCP\\ICacheFacto...', true)
#20 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OCP\\ICacheFacto...')
2023-08-11T14:30:11.189732341Z #21 /var/www/html/lib/private/Server.php(1115): OC\AppFramework\Utility\SimpleContainer->get('OCP\\ICacheFacto...')
2023-08-11T14:30:11.189736040Z #22 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
2023-08-11T14:30:11.189739749Z #23 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
2023-08-11T14:30:11.189745849Z #24 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
2023-08-11T14:30:11.189749421Z #25 /var/www/html/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OCP\\Lock\\ILocki...', true)
2023-08-11T14:30:11.189752258Z #26 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
2023-08-11T14:30:11.189754971Z #27 /var/www/html/lib/private/Server.php(2067): OC\AppFramework\Utility\SimpleContainer->get('OCP\\Lock\\ILocki...')
2023-08-11T14:30:11.189771342Z #28 /var/www/html/lib/private/Files/View.php(106): OC\Server->getLockingProvider()
2023-08-11T14:30:11.189774406Z #29 /var/www/html/lib/private/Server.php(467): OC\Files\View->__construct()
2023-08-11T14:30:11.189777060Z #30 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\Server->OC\{closure}(Object(OC\Server))
2023-08-11T14:30:11.189779810Z #31 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
2023-08-11T14:30:11.189782554Z #32 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OC\\Files\\Node\\H...')
2023-08-11T14:30:11.1897
#33 /var/www/html/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OC\\Files\\Node\\H...', true)
2023-08-11T14:30:11.189788032Z #34 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\ServerContainer->query('OC\\Files\\Node\\H...')
2023-08-11T14:30:11.189790697Z #35 /var/www/html/lib/private/Server.php(1469): OC\AppFramework\Utility\SimpleContainer->get('OC\\Files\\Node\\H...')
2023-08-11T14:30:11.189793942Z #36 /var/www/html/lib/base.php(638): OC\Server->boot()
2023-08-11T14:30:11.189797121Z #37 /var/www/html/lib/base.php(1180): OC::init()
2023-08-11T14:30:11.189799818Z #38 /var/www/html/console.php(48): require_once('/var/www/html/l...')
2023-08-11T14:30:11.189802566Z #39 /var/www/html/occ(11): require_once('/var/www/html/c...')
2023-08-11T14:30:11.195817744Z #40 {main}==> Failed at executing "/docker-entrypoint-hooks.d/before-starting/00_post-start.sh". Exit code: 1
```

When i open a shell in the container with `su -s /bin/sh www-data` and run the script `sh -c "/docker-entrypoint-hooks.d/before-starting/00_post-start.sh"` it is working without problems.

I've no idea why the occ command wan't a postgesql.crt from the roots home. Since i'm www-data i've also tried it with `php occ app:disable dashboard" but that isn't working either.

**Comment by jpuskar** [comment]
I've been chasing the same thing for 4 days; I thought I was just me!

**Comment by joshtrichards** [comment]
Assuming you're not actually using a client certificate, this may workaround the issue:

`sh -c "unset HOME && php occ $1"`

The error has to do with (IIRC - take this with a grain of salt): the PostgreSQL client and a mixture of different fallbacks for SSL connection modes which can sometimes end up trying (to look for) client-side certificates. In this case it sounds like $HOME is set to `/root` still (probably inherited from the container execution) so it's trying to look for a client cert there. When that fails due to permissions (understandable) it considers it fatal. Unbeknownst to the pg client, it doesn't matter *to you* that it can't find any certs - because you're likely not using any (and, in any case, if you were that's not where you'd have them).

There are some other factors IIRC, like your server-side `pg_hba.conf` `ssl*` parameters and maybe pg version differences, that I don't recall off the top of my head at the moment.

I do see another issue (at least in the example you provided):

> `run_as app:disable dashboard`

Since `run_as` references `$1` to grab it's parameters, you need to put quotes around the above or the `dashboard` will get dropped - e.g:

`run_as "app:disable dashboard"`

**Comment by mueller-tobias** [comment]
Thansk @joshtrichards. The trick with the unset HOEM did it. I checked. I'm using v27.0.1.
We're running the image in kubernetes and the helm chart didn't received the update to the 27.0.2 image as the default image yet.

But it's strange that

**Comment by StrikerRUS** [comment]
@joshtrichards Thanks a lot for the `unset HOME` suggestion! I used

```yml
environment:
  - HOME=""
```
in my docker compose file to make Nextcloud 29 work with my external PostgreSQL server which is configured to accept only SSL connections (no certs).

**Comment by pando85** [comment]
I fixed it by setting PGSSLCERT envar to `/tmp/postgresql.crt`: [commit with the fix](https://github.com/pando85/homelab/commit/b14cabb50267267a342c71154df4a2bb79f05dec)

More detailed explanation in this [here](https://github.com/bitnami/containers/issues/65832#issuecomment-2126939552)
