### ISSUE TITLE
[GH-Actions] Image build failed for 28.0.3/27.1.7/26.0.12

### ISSUE THREAD

**Issue by koelle25** [nextcloud/docker#2171]
The image build automation fail in the `test` stage with an error regarding the Postgres DB (see https://github.com/nextcloud/docker/actions/runs/8134160455):
```
Initializing nextcloud 26.0.12.2 ...
New nextcloud instance
Installing with PostgreSQL database
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/pre-installation
Starting nextcloud installation
PostgreSQL username and/or password not valid
 -> You need to enter details of an existing account.
Trace: #0 /var/www/html/lib/private/Setup.php(353): OC\Setup\PostgreSQL->setupDatabase('test_14627')
#1 /var/www/html/core/Command/Maintenance/Install.php(104): OC\Setup->install(Array)
#2 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/console.php(100): OC\Console\Application->run()
#8 /var/www/html/occ(11): require_once('/var/www/html/c...')
#9 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "db" (172.17.0.2), port 5432 failed: FATAL:  database "test_8740_db" does not exist
Trace: #0 /var/www/html/lib/private/Setup/PostgreSQL.php(112): OC\DB\Connection->connect()
#1 /var/www/html/lib/private/Setup.php(353): OC\Setup\PostgreSQL->setupDatabase('test_14627')
#2 /var/www/html/core/Command/Maintenance/Install.php(104): OC\Setup->install(Array)
#3 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Install), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/console.php(100): OC\Console\Application->run()
#9 /var/www/html/occ(11): require_once('/var/www/html/c...')
#10 {main}
```
It's the same error for every image variant (only the database names are different).

**Comment by pierreozoux** [comment]
maybe they are flacky, I started them again:
https://github.com/nextcloud/docker/actions/runs/8134160455

**Comment by pierreozoux** [comment]
ok, not flacky :sweat_smile:

**Comment by JonnyTischbein** [comment]
I tried to look into this, but am I a bit confused about the workflow.
The test only tries to connect to postgres and it is not a build error but a test setup error right ?

I found the [travis file](https://github.com/nextcloud/docker/blob/master/.travis/test-example-dockerfiles.sh) which just builds the image but I didn't find the ` /home/runner/oi/test/run.sh nextcloud:28.0.3-apache` which runs the test.

Do you know where I have to look ?

**Comment by kolaente** [comment]
Looks like the build still failed for production images: https://github.com/nextcloud/docker/actions/runs/8146934616/job/22266579741

**Comment by realDayaa** [comment]
Any idea on why it still keeps failing?
