### ISSUE TITLE
login/uploading one image has an added delay of about ~30 seconds

### ISSUE THREAD

**Issue by dachary** [nextcloud/docker#293]
The details are [in the forum](https://help.nextcloud.com/t/with-a-standard-docker-deployed-nexcloud-13-login-takes-30-seconds/29470) and repeated here for the record:

Nextcloud version _12 and 13_:
Operating system and version _Debian 9_:
Apache or nginx version _[Docker / nginx proxy / apache](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache)_: 

The issue you are facing:

On both instances (one nextcloud 12 and the other nextcloud 13) deployed in the same way

Is this the first time you've seen this error? _N_:

Steps to replicate it:

1. git clone https://github.com/nextcloud/docker
2. cd .examples/docker-compose/with-nginx-proxy/postgres/apache
3. sudo docker-compose up -d
4. go to https://cloud.mycloud.com/ and login
5. it takes ~30 seconds to load /app/files

During these 30 seconds, the CPU and the I/O are mostly idle.

There are no additional lines in  **Admin > Logging**:

The output of your Apache/nginx/system log in `/var/log/____`:
```
sudo docker-compose logs -f proxy
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:20 +0000] "GET /login HTTP/2.0" 200 3115 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:21 +0000] "GET /cron.php HTTP/2.0" 200 20 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:54 +0000] "POST /login HTTP/2.0" 303 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:54 +0000] "GET /apps/files/ HTTP/2.0" 200 6341 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:55 +0000] "GET /apps/gallery/config?extramediatypes=1 HTTP/2.0" 200 102 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:55 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:56 +0000] "GET /apps/encryption/ajax/getStatus HTTP/2.0" 200 77 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:56 +0000] "PROPFIND /remote.php/webdav/ HTTP/2.0" 207 4598 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:56 +0000] "GET /apps/systemtags/lastused HTTP/2.0" 200 9 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:56 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/2.0" 200 189 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:09:56 +0000] "GET /cron.php HTTP/2.0" 200 20 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
proxy_1                  | nginx.1    | XXXXXXXXXXXXXX - - [25/Mar/2018:12:10:25 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"

```

**Comment by dachary** [comment]
Uploading a single image also takes around 30 seconds. As if there was a request done to something that eventually timesout after 30 seconds... but what?

<pre>
~/docker/.examples/docker-compose/with-nginx-proxy/postgres/apache$ sudo docker-compose logs --tail=200 -f app
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:30 +0000] "GET /ocs/v1.php/cloud/users/loic?format=json HTTP/1.1" 200 897 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:31 +0000] "GET /status.php HTTP/1.1" 200 1023 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:31 +0000] "GET /index.php/avatar/loic/256 HTTP/1.1" 304 247 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:31 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 2230 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:31 +0000] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 898 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:32 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1358 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:32 +0000] "GET /ocs/v2.php/apps/files_sharing/api/v1/shares?path=%2F&reshares=true&subfiles=true HTTP/1.1" 200 736 "-" "Mozilla/5.0 (Android) own\
Cloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:39 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 2230 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:40 +0000] "GET /ocs/v1.php/cloud/users/loic?format=json HTTP/1.1" 200 897 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:40 +0000] "GET /ocs/v1.php/cloud/users/loic?format=json HTTP/1.1" 200 897 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:40 +0000] "GET /index.php/avatar/loic/256 HTTP/1.1" 304 247 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:29:31 +0000] "GET /index.php/204 HTTP/1.1" 204 1423 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:30:01 +0000] "HEAD /remote.php/webdav/IMG_20180118_134348.jpg HTTP/1.1" 404 526 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:30:02 +0000] "PUT /remote.php/webdav/IMG_20180118_134348.jpg-chunking-679502994-2-0 HTTP/1.1" 201 537 "-" "Mozilla/5.0 (Android) ownCloud-android/3.\
0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:30:03 +0000] "PUT /remote.php/webdav/IMG_20180118_134348.jpg-chunking-679502994-2-1 HTTP/1.1" 201 675 "-" "Mozilla/5.0 (Android) ownCloud-android/3.\
0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:30:03 +0000] "PROPFIND /remote.php/webdav/IMG_20180118_134348.jpg HTTP/1.1" 207 1422 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:13:30:04 +0000] "GET /index.php/apps/files/api/v1/thumbnail/256/256/IMG_20180118_134348.jpg HTTP/1.1" 200 17672 "-" "Mozilla/5.0 (Android) ownCloud-and\
roid/3.0.3"
</pre>

**Comment by dachary** [comment]
When uploading an image from the web interface on a desktop to this same Docker instance, there is no delay
<pre>
app_1                    | 172.19.0.2 - loic [25/Mar/2018:20:32:50 +0000] "GET /index.php/204 HTTP/1.1" 204 1419 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:38 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 689 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
app_1                    | 172.19.0.2 - loic [25/Mar/2018:20:33:21 +0000] "GET /index.php/204 HTTP/1.1" 204 1425 "-" "Mozilla/5.0 (Android) ownCloud-android/3.0.3"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:53 +0000] "PUT /remote.php/webdav/copy.png HTTP/1.1" 201 657 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:54 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php HTTP/1.1" 200 1073 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:54 +0000] "PROPFIND /remote.php/webdav/copy.png HTTP/1.1" 207 1566 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:54 +0000] "GET /core/preview.png?file=%2Fcopy.png&c=3d832903e6149d269706b0010270df52&x=64&y=64&forceIcon=0 HTTP/1.1" 200 7073 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
app_1                    | 172.19.0.2 - - [25/Mar/2018:20:33:54 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1073 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
</pre>

**Comment by dachary** [comment]
I [activated debug](https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html) and

* edit config/config.php to add **'debug' => true**
* restart the container with 
* sudo docker-compose exec app tail -f data/nextcloud.log and I see 
<pre>
{"reqId":"qXV9Zix6R4TFZvZTZDnw","level":2,"time":"2018-03-25T15:21:19+00:00","remoteAddr":"172.19.0.2","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"172.1
9.0.2\" tried to access using \"149.202.165.105\" as host.","userAgent":"--","version":"13.0.1.1"}                                                                                                
{"reqId":"DbEH3HFB0iEuadABg4AB","level":3,"time":"2018-03-25T20:44:21+00:00","remoteAddr":"172.19.0.2","user":"loic","app":"index","method":"GET","url":"\/index.php\/204","message":"Exception: {
\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_preferences\\\" SET \\\"configvalue\\\" = ? WHERE (\\\"useri
d\\\" = ?) AND (\\\"appid\\\" = ?) AND (\\\"configkey\\\" = ?)' with params [1522010661, \\\"loic\\\", \\\"login\\\", \\\"lastLogin\\\"]:\\n\\nSQLSTATE[HY000]: General error: 5 database is locke
d\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->co$
vertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php($
015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc$
pref...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#3 \\\/var\\\$
www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#4 \\\/v$
r\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AllConfi$
.php(234): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/User.php(191): OC\\\\AllConfig->setUserValue('loic', 'login', 'lastLogin'$
 1522010661)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(366): OC\\\\User\\\\User->updateLastLoginTimestamp()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/S$
ssion.php(564): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(335): OC\\\\User\\\\Session->log$
nWithPassword(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced *$
*)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/b$
se.php(1052): OC\\\\User\\\\Session->tryBasicAuthLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\Security\\\\Bruteforce\\\\Throttler))\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/b$se.php(987): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#14 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\$/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"13.0.1.1"}
{"reqId":"sQWQJHGkeTZippEcZokD","level":3,"time":"2018-03-25T20:44:21+00:00","remoteAddr":"172.19.0.2","user":"loic","app":"index","method":"GET","url":"\/index.php\/204","message":"Exception: $\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_preferences\\\" SET \\\"configvalue\\\" = ? WHERE (\\\"user$d\\\" = ?) AND (\\\"appid\\\" = ?) AND (\\\"configkey\\\" = ?)' with params [1522010661, \\\"loic\\\", \\\"login\\\", \\\"lastLogin\\\"]:\\n\\nSQLSTATE[HY000]: General error: 5 database is lock$d\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->co$vertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php($015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc$pref...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/Connection.php(216): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#3 \\\/var\\\$www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#4 \\\/v$r\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AllConfi$.php(234): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/User.php(191): OC\\\\AllConfig->setUserValue('loic', 'login', 'lastLogin'$ 1522010661)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(366): OC\\\\User\\\\User->updateLastLoginTimestamp()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/S$ssion.php(564): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(335): OC\\\\User\\\\Session->log$nWithPassword(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\User\\\\Session->login(*** sensitive parameters replaced *$
*)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/b$
se.php(1052): OC\\\\User\\\\Session->tryBasicAuthLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\Security\\\\Bruteforce\\\\Throttler))\\n#13 \\\/var\\\/www\\\/html\\\/lib\\\/b$
se.php(987): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#14 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\$
/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"13.0.1.1"}
{"reqId":"DUJqhnGwqo7rlr6MK3Y1","level":2,"time":"2018-03-25T21:09:12+00:00","remoteAddr":"172.19.0.2","user":"--","app":"core","method":"HEAD","url":"\/remote.php\/webdav\/","message":"Login f$
iled: '' (Remote IP: '172.19.0.2')","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"13.0.1.1"}
</pre>

**Comment by dachary** [comment]
The **Admin Logging** panel shows a number of lines like:

<pre>
Warning	core	Login failed: 'Max' (Remote IP: '172.19.0.2')	2018-03-25T23:47:30+0200
</pre>

There is no user **Max** meaning it's brute force attack but... this was [deployed using Docker](https://github.com/nextcloud/docker) and all requests incorrectly originate from the same IP **172.19.0.2**. So, as soon as anyone makes too many failed login attempts everyone is blocked.

**Comment by dachary** [comment]
I believe the root cause of this issue is because [All requests originate from 172.19.0.2](https://github.com/nextcloud/docker/issues/294) causing general throttling for everyone after a brute force attack.
