### ISSUE TITLE
Upgrade not working - Operation not permitted

### ISSUE THREAD

**Issue by cwrau** [nextcloud/docker#314]
After starting my Nextcloud again after ~4 weeks, it greeted me with an 'Upgrade available' message.
Therefore I went to my console, and ran 'sudo -u www-data ./occ upgrade'

```
sudo -u www-data ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app announcementcenter in appstore
Checked for update of app "announcementcenter" in appstore
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_external in appstore
Checked for update of app "files_external" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
Starting code integrity check...
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/docs\/userguide\/dbaas.md): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/docs\/getting-started.md): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/docs\/getting-started-openstack.md): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/docs\/generate.sh): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/CONTRIBUTING.md): failed to openstream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/CODE_OF_CONDUCT.md): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/.coveralls.yml): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/.gitignore): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:41+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/rackspace\/php-opencloud\/README.md): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/.drone.yml): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/LICENSE INFO): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/.gitignore): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/3rdparty\/README.md): failed to open stream: Operation not permittedat \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/public.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/status.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/remote.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/robots.txt): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/index.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_file(\/var\/www\/html\/AUTHORS): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/IntegrityCheck\/Checker.php#229","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"include(\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOException.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"include(): Failed opening '\/var\/www\/html\/3rdparty\/composer\/..\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOException.php' for inclusion (include_path='\/var\/www\/html\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/apps') at \/var\/www\/html\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"include(\/var\/www\/html\/3rdparty\/symfony\/debug\/Exception\/FatalThrowableError.php): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"--","version":"13.0.0.14"}
{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"include(): Failed opening '\/var\/www\/html\/3rdparty\/composer\/..\/symfony\/debug\/Exception\/FatalThrowableError.php' for inclusion (include_path='\/var\/www\/html\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/apps') at \/var\/www\/html\/lib\/composer\/composer\/ClassLoader.php#443","userAgent":"--","version":"13.0.0.14"}
An unhandled exception has been thrown:
Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/html/3rdparty/symfony/console/Application.php:134
Stack trace:
#0 /var/www/html/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/console.php(90): OC\Console\Application->run()
#2 /var/www/html/occ(11): require_once('/var/www/html/c...')
#3 {main}{"reqId":"GRCR7cnHH96qG0h4gfJ2","level":3,"time":"2018-04-17T12:04:42+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"fopen(\/var\/www\/html\/data\/nextcloud.log): failed to open stream: Operation not permitted at \/var\/www\/html\/lib\/private\/Log\/File.php#135","userAgent":"--","version":"13.0.0.14"}
```

As you can  see, there are some weird 'Operation not permitted' errors.
I `chown www-data:www-data -R .` the /var/www/data folder, but it still gives me the same error.

Is there something I did wrong? Bad Configuration? I'd be glad to give you any info you may require.
I'm using the `nextcloud:apache` image

**Comment by J0WI** [comment]
You should use `docker exec -itu www-data` and then `./occ upgrade`. Or just set the `NEXTCLOUD_UPDATE` env. Please note that skipping major releases is not supported.

I hope this solves your problem, please feel free to open a issue with newer details otherwise.
