### ISSUE TITLE
Uncaught Exception: Could not gather sufficient random data

### ISSUE THREAD

**Issue by dionysiusmarquis** [nextcloud/docker#35]
Hey,

after i pulled the current Docker image (22e6f0d29aea) i got this error:

```
Updating permissions...
Updating permissions in /nextcloud...
Permissions in /data are correct.
Permissions in /config are correct.
Permissions in /apps2 are correct.
Updating permissions in /etc/nginx...
Updating permissions in /etc/php7.1...
Updating permissions in /var/log...
Updating permissions in /var/lib/nginx...
Updating permissions in /tmp...
Updating permissions in /etc/s6.d...
Done updating permissions.
Starting automatic configuration...
PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /nextcloud/lib/private/Security/SecureRandom.php:81
Stack trace:
#0 /nextcloud/lib/private/Security/SecureRandom.php(81): random_int(0, 63)
#1 /nextcloud/lib/private/AppFramework/Http/Request.php(576): OC\Security\SecureRandom-&gt;generate(20)
#2 /nextcloud/lib/private/Log/File.php(93): OC\AppFramework\Http\Request-&gt;getId()
#3 [internal function]: OC\Log\File::write('PHP', 'Exception: Coul...', 3)
#4 /nextcloud/lib/private/Log.php(300): call_user_func(Array, 'PHP', 'Exception: Coul...', 3)
#5 /nextcloud/lib/private/Log.php(158): OC\Log-&gt;log(3, 'Exception: Coul...', Array)
#6 /nextcloud/lib/private/Log/ErrorHandler.php(81): OC\Log-&gt;critical('Exception: Coul...', Array)
#7 [internal function]: OC\Log\ErrorHandler::onException(Object(Exception))
#8 {main}
```

**Comment by Wonderfall** [comment]
It seems you're using my image wonderfall/nextcloud, which is not the official one.
I invite you to reopen your issue there : https://github.com/Wonderfall/dockerfiles/issues
Thanks. :)

**Comment by Steiniche** [comment]
Hi @Wonderfall it seem that this issue is not related to Nextcloud but rather the usage of PHP 7.1.2
However, it seems that this repo / docker container is using 7.0.18 which obviously also must have the problem, as I am seeing it as well.
Is there any chance for a move to PHP 7.1.4 or will we have to build such a container our self?
