### ISSUE TITLE
Failed to connect to database after 14.0.2 > 14.0.3 upgrade

### ISSUE THREAD

**Issue by reppard** [nextcloud/docker#521]
After upgrading from 14.0.2 to 14.0.3 Nextcloud can't connect to my database. I can connect to the database manually with a mysql client.  Downgrading back to 14.0.2 throws another error stating that downgrading isn't supported.

```
nextcloud_1  | [Tue Oct 23 02:32:50.799872 2018] [php7:error] [pid 30] [client 172.19.0.1:50410] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /var/www/html/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()
#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()
#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)
#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), in /var/www/html/lib/private/DB/Connection.php on line 64
```

**Comment by reppard** [comment]
@pepz-de if you haven't been able to downgrade, I was able to do so by removing everything in my 'html' directory and letting the 14.0.2 container regenerate that. I had to reinstall all my apps but it got me running again.

**Comment by bambuleee** [comment]
I'm using an external container. Latest mariadb release.
Reinstalling all apps is no solution atm.

**Comment by SnowMB** [comment]
What database and version are you using?

**Comment by bambuleee** [comment]
10.3.10

I think I fixed it adding
[mysqld]                                                                                                                                                                                                                                      
default_authentication_plugin=mysql_native_password   

in custom.cnf from the maraidb-container.

Source: https://help.nextcloud.com/t/nextcloud-13-php-7-1-mysql-8-error-500/34443

**Comment by reppard** [comment]
> What database and version are you using?

I've been using the vanilla `mysql:8.0` container
