### ISSUE TITLE
The switch to from php:7.2-apache-stretch to php:7.3-apache-stretch breaks user_saml

### ISSUE THREAD

**Issue by pfy** [nextcloud/docker#714]
We use user_saml and it works if we use the current Dockerfile and replace php:7.3-apache-stretch with php:7.2-apache-stretch. On php 7.3 we get the following error
```
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.
Technical details

Remote Address: -----
Request ID: FO3UTkiXHWzmuDLPdXo6
Type: Error
Code: 0
Message: Call to a member function item() on bool
File: /var/www/html/custom_apps/user_saml/3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php
Line: 501

Trace

#0 /var/www/html/custom_apps/user_saml/3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php(591): RobRichards\XMLSecLibs\XMLSecurityDSig->processRefNode(Object(DOMElement))
#1 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php(1412): RobRichards\XMLSecLibs\XMLSecurityDSig->validateReference()
#2 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php(410): OneLogin\Saml2\Utils::validateSign(Object(DOMDocument), '-----BEGIN CERT...', '', 'sha1', '/samlp:Response...', NULL)
#3 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php(226): OneLogin\Saml2\Response->isValid('ONELOGIN_7c7274...')
#4 /var/www/html/custom_apps/user_saml/lib/Controller/SAMLController.php(251): OneLogin\Saml2\Auth->processResponse('ONELOGIN_7c7274...')
#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\User_SAML\Controller\SAMLController->assertionConsumerService()
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\User_SAML\Controller\SAMLController), 'assertionConsum...')
#7 /var/www/html/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\User_SAML\Controller\SAMLController), 'assertionConsum...')
#8 /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\User_SAML\\C...', 'assertionConsum...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#10 /var/www/html/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#11 /var/www/html/lib/base.php(987): OC\Route\Router->match('/apps/user_saml...')
#12 /var/www/html/index.php(42): OC::handleRequest()
#13 {main}
```

**Comment by ChessSpider** [comment]
still broken?

**Comment by pfy** [comment]
user_saml 2.2.0 fixes the problem
