### ISSUE TITLE
docker-compose nextcloud fpm fails with exception

### ISSUE THREAD

**Issue by gregf** [nextcloud/docker#969]
Just using the default docker-compose from the readme only changes are the mysql passwords.

```
ERROR: for d5e7c893a344_nextcloud_web_1  a bytes-like object is required, not 'str'

ERROR: for web  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.22/containers/5c78171f05009d51ec5da431ac4c670a6d0d19774998fab1343c13954c8bfb6f/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 400 Client Error: Bad Request ("b'OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/root/nextcloud/nginx.conf\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/ce692825e1b08e259ee2451210d9fa0e5f5cd3a47780dc1923047d840940711f/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/ce692825e1b08e259ee2451210d9fa0e5f5cd3a47780dc1923047d840940711f/merged/etc/nginx/nginx.conf\\\\\\" caused \\\\\\"not a directory\\\\\\"\\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 563, in execute_convergence_plan
  File "compose/service.py", line 490, in _execute_convergence_recreate
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 483, in recreate
  File "compose/service.py", line 602, in recreate_container
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[80897] Failed to execute script docker-compose
```

**Comment by LarsBauer** [comment]
Are you providing a `nginx.conf` at the specified path? You can download a working configuration from the `.examples` directory in the repo and place it next to your `docker-compose.yml`.

**Comment by gregf** [comment]
That was the problem, not super familiar with docker. Thank you.
